### ISSUE TITLE
[RFC0018] Lopenling V.0.1

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#110]
<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

[RFC0018] Lopenling v.0.1

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

 - [Remix](https://remix.run/)    ` Full stack `
 - [Prisma](https://www.prisma.io/)  ` Database ORM `
 - [Tiptap](https://tiptap.dev/)   `Rich text editor`
 - [Flowbite](https://flowbite.com/)  `UI`

<h2 id="summary">Summary</h2>

This request pertains to the development of an application platform that facilitates discussions on texts by enabling users to select specific topics within the text, post questions, and leave comments.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

- create a new [Remix](https://remix.run/) application
- integrate  [Prisma](https://www.prisma.io/) with Postgres setup for Database

![image](https://user-images.githubusercontent.com/42644738/213092857-913d7882-f21c-49a2-878b-68110ea6b369.png)
 -  there will be two route as shown above

1.  Homepage '/'

- include search engine for the text in database

2. Editorpage '/text/[textId]'

![image](https://user-images.githubusercontent.com/42644738/213095333-1d938930-9053-4015-9763-0a4281042c3a.png)

- text will be rendered on the page with [tiptap](https://tiptap.dev/) 'rich text editor'
- A bubble menu will appear when selecting text , this includes comments and question
- clicking on each of them will render its component on the right side of the screen 

</em>

3. Database

1. User ->id, email , username , is_admin , role
2. Post ->id, type ,avatar, topic_id , text_id , user_id, post_id , start , end , avatar ,content, likedBy   
3. Replies -> id, parentPost, likeBy , approved, 
4. Text ->id,  name, content

<h2 id="alternatives">Alternatives</h2>

we can use other text editor or have no rich text editor and render text with our own components

<h3 id="rationale">Rationale</h3>

<em>

- with Tiptap selection of text and and getting its address in the unchanging content will be much easier 
- we would need to write a separate code for selection and getting the location of selection .
</em>

<h2 id="drawbacks">Drawbacks</h2>

there will be some issues left with long text rendering and mapping for the selection

<h2 id="useful-rererences">Useful References</h2>

*Describe useful parallels and learnings from other requests, or work in previous projects.*

<em>
  
- What similar work have we already successfully completed?
- Is this something that have already been built by others?
- What other related learnings we have?
- Are there useful academic literature or other articles related with this topic? (provide links)
- Have we built a relevant prototype previously?
- Do we have a rough mock for the UI/UX?
- Do we have a schematic for the system?

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?
- Are there other requests with same or similar problems to solve?
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?
- What other open requests are closely related with this request?
- Does this request depend on fulfillment of any other request?
- Does any other request depend on the fulfillment of this request?*

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

*How do you see the particular system or part of the system affected by this request be altered or extended in the future.*

<h2 id="infrastructure">Infrastructure</h2>

this is the First version of the App so there is no change in Infrastructure 

<h2 id="testing">Testing</h2>

- [ ] unit testing once the project is ready

<h2 id="documentation">Documentation</h2>

*Describe the level of documentation fulfilling this request involves. Consider both end-user documentation and developer documentation.*

<h2 id="version-history">Version History</h2>

version 0.1

<h2 id="recordings">Recordings</h2>

*Links to audio recordings of related discussion.*

## Work Phases
<h2 id="work-phases"></h2>

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#6
  - Time Estimation : 1:30 hours.
  - Time Taken :  30 min.

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#11
  - Time Estimation : 4:30 hours.
  - Time Taken :  4 hours

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#12
  - Time Estimation : 4 hours.
  - Time Taken : 3 hours

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#13
  - Time Estimation : 4 hours.
  - Time Taken :4 hours.

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#9
  - Time Estimation : 15 hours.
  - Time Taken : 3 hours. 

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#8
    -Time Estimation: 5 hours.
    -Time Taken : 3 hours.  

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#3
    -Time Estimation: 3 hours.
    -Time Taken :   3hours

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#7
    -Time Estimation: 3 hours.
    -Time Taken : 2 hours  

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#5
  - Time Estimation : 12 hours.
  - Time Taken : 10 hours

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#10
  - Time Estimation : 16 hours.
  - Time Taken : 10 hours

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#4
  -  Time Estimation: 8 hours
  -  Time Taken : 8 hours

- [x] OpenPecha/Lopenling-app-cloudflare-v0.1#15
  -  Time Estimation: 8 hours
  -  Time Taken :  4 hours

- [x] OpenPecha/Lopenling-App#19
  -  Time Estimation: 2 hours
  -  Time Taken :  4hours
  
- [x] OpenPecha/Lopenling-App#20
  -  Time Estimation: 3 hours
  -  Time Taken :  2 hours

- [x] OpenPecha/Lopenling-App#24
  -  Time Estimation: 3 hours
  -  Time Taken : 
  
 - [x] OpenPecha/Lopenling-App#25
 -  Time Estimation: 3 hours
 -  Time Taken:

 - [x] OpenPecha/Lopenling-App#29
 -  Time Estimation: 3 hours
 -  Time Taken: 4 hour

 Total time estimation: 94 hours 

 
*Keep original naming and structure, and keep as first section in Work phases section*

  - [x] Planning
  - [ ] Documentation
  - [x] Testing

<h3 id="implementation">Implementation</h3>

*A list of checkboxes, one per PR. Each PR should have a descriptive name that clearly illustrates what the work phase is about.*
