### ISSUE TITLE
[RFC0042] Lopenling v0.2

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#138]
## Work Planning

<details>
  <summary>Details</summary>

<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

[RFC0042] Lopenling v0.2

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

*Explain any new concepts introduced in this request.*

<h2 id="summary">Summary</h2>

this request is about adding a suggestion feature on lopenling app and recording and uploading audio while creating a comment and question.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

- As the build of this version of lopenling is bigger in size we will be hosting it on another server.
- the audio will be uploaded to s3 server and the link to the file will be used.

<h2 id="alternatives">Alternatives</h2>

we checked ckEditor for our feature requirement and come to conclusion that eventhough it is a powerful editor, it will be hard to modify its UI according to our requirement.  we will continue using the tiptap for this version.

<h3 id="rationale">Rationale</h3>

<em>

- Why the currently proposed design was selected over alternatives?
- What would be the impact of going with one of the alternative approaches?
- Is the evaluation tentative, or is it recommended to use more time to evaluate different approaches?
</em>

<h2 id="drawbacks">Drawbacks</h2>

the created mark on the text will be saved on the database with text. this might create issue on large text.

<h2 id="useful-rererences">Useful References</h2>

*Describe useful parallels and learnings from other requests, or work in previous projects.*

<em>
  
- What similar work have we already successfully completed?
- Is this something that have already been built by others?
- What other related learnings we have?
- Are there useful academic literature or other articles related with this topic? (provide links)
- Have we built a relevant prototype previously?
- Do we have a rough mock for the UI/UX?
- Do we have a schematic for the system?

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?
- Are there other requests with same or similar problems to solve?
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?
- What other open requests are closely related with this request?
- Does this request depend on fulfillment of any other request?
- Does any other request depend on the fulfillment of this request?*

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

*How do you see the particular system or part of the system affected by this request be altered or extended in the future.*

<h2 id="infrastructure">Infrastructure</h2>

*Describe the new infrastructure or changes in current infrastructure required to fulfill this request.*

<h2 id="testing">Testing</h2>

*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

<h2 id="documentation">Documentation</h2>

*Describe the level of documentation fulfilling this request involves. Consider both end-user documentation and developer documentation.*

<h2 id="version-history">Version History</h2>

*History of changes to this RFC. Following semantic versioning pattern and v0.1.2 for style.*

<h2 id="recordings">Recordings</h2>

*Links to audio recordings of related discussion.*

</details>

 
<h2 id="work-phases">Work Phases</h2>

<h3 id="non-coding">Planning</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

- [x] RFC completed on: 
      Estimated time: 
      Actual time: 
- [ ] RFC reviewed and approved by: 
      Estimated time: 
      Actual time: 

<h3 id="implementation">Implementation</h3>

*A list of checkboxes, one per PR. Each PR should have a descriptive name that clearly illustrates what the work phase is about.*
- [x] OpenPecha/Lopenling-App-v2#2
      Estimated time: 2day
      Actual time: 2day

- [x] OpenPecha/Lopenling-App-v2#3
      Estimated time:  2day
      Actual time: 1day

- [x] OpenPecha/Lopenling-App-v2#4
      Estimated time:  2day
      Actual time: 3 days

- [x] OpenPecha/Lopenling-App-v2#5
      Estimated time:  1 day
      Actual time: 3 days

- [x] OpenPecha/Lopenling-App-v2#7
      Estimated time:  1 day
      Actual time: 2 day

- [x] OpenPecha/Lopenling-App-v2#8
      Estimated time:  1 day
      Actual time: 1 day

- [x] OpenPecha/Lopenling-App-v2#9
      Estimated time:  1 day
      Actual time: 1day

- [x] OpenPecha/Lopenling-App-v2#10
      Estimated time:  1day
      Actual time:  2 day 

- [x] OpenPecha/Lopenling-App-v2#12
      Estimated time:  1day
      Actual time: 

<h3 id="implementation">Completion</h3>

- [ ] Tested and approved by: @username, @username
      Estimated time: 
      Actual time: 
- [ ] Documentation approved @evanyerburgh
      Estimated time: 
      Actual time:
