### ISSUE TITLE
[RFC0069] Modify Community page (Pecha.org)

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Requests#280]
# RFC0069: *Modify Community Page*

## Named Concepts
Django: Python-based web framework that follows the model–template–views architectural pattern.
React: An open-source front-end JavaScript library for building user interfaces based on components.
Transifex: A management system for automation of the localization workflow by integrating with common developer tools.
Mongodb: Easy for developers to store, manage, and retrieve data when creating applications with most programming languages

## Summary
*The Community page in Pecha.org is one the main feature beside Text page that need modification from Sefaria's way of implementation. From Community page, users can navigate to several other useful page (such as, Collection page and Sheet page) that also need to be modify, so I have added them as well under implementation steps.*

## Infrastructure
Local Development : The environment is setup locally to test application development.
CI/CD : github action
Staging Environment : Deployed with staging branch on render
Production Deployment : Deployed with master branch on render

## Testing
*Pecha application should run locally to test the changes related with uploading text with Sefaria api.*

## Implementation Steps
*List all the steps involved during implementation.*

- [x] OpenPecha/Pecha.org#67
      Estimated time:  30min
      Actual time:  
- [x] OpenPecha/Pecha.org#68
      Estimated time:  10min
      Actual time:  
- [x] OpenPecha/Pecha.org#69
      Estimated time:  30min
      Actual time:  
- [x] OpenPecha/Pecha.org#51
      Estimated time:  1hour
      Actual time: 
- [x] OpenPecha/Pecha.org#54
      Estimated time:  3hour
      Actual time: 
- [x] OpenPecha/Pecha.org#55
      Estimated time:  3hour
      Actual time:  
- [x] OpenPecha/Pecha.org#58
      Estimated time:  2hour
      Actual time: 
- [x] OpenPecha/Pecha.org#74
      Estimated time:  1hour
      Actual time:
- [x] OpenPecha/Pecha.org#73
      Estimated time:  2hour
      Actual time:
- [x] OpenPecha/Pecha.org#59
      Estimated time:  3hour
      Actual time:   
- [ ] OpenPecha/Pecha.org#57
      Estimated time:  3hour
      Actual time: 
- [x] OpenPecha/Pecha.org#95
      Estimated time:  4hour
      Actual time:
- [x] OpenPecha/Pecha.org#97
      Estimated time:  4hour
      Actual time:
- [ ] OpenPecha/Pecha.org#96
      Estimated time:  4hour
      Actual time:

## Reviewed By

@tenkus47
