### ISSUE TITLE
[RFC0074] sampling images of works

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/Requests#297]
# RFC00: *RFC Title*

## Named Concepts
pillow : pillow is used for image processing
S3: images are stored on s3 bucket

## Summary
We have json with all the work ids and the instances that the work has at [jsons](https://github.com/OpenPecha/filtering_work_data/tree/main/data/json). Use this json files to go through each work id and check if its instance's print method is not modern print. if it is not modern print then need to random take a volume from the work and then download 10 random images from that volume and put those 10 images together on a single image so that it can be compared. We need to store the images and volume infos of the images used in a dict or a list.

## Dependencies
None

## Infrastructures
*Include all the infrastructure required for running the task, such as S3 bucket, EC2 server, etc.*

## Design Illustrations
*Include all the pictorial representation of your implementation, such as flowchart, ER diagram, etc.*

## Justification
this way we can compare the 10 images at once on a single image to be categorize in the writing style or the fonts.

## Testing
*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] Get all the jsons into a single json and then script to parse the json
      Estimated time:  3 hrs
      Actual time:  
- [ ] get the volumes of the work id and randomly take one, randomly take 10 images from the volume
      Estimated time:  3 hrs
      Actual time:  
- [ ]  download the images and then put them together in a single image, keep the info in a dict
      Estimated time:  3 hrs
      Actual time:  

## Reviewed By
*Who has reviewed the RFC?*

**Comment by ta4tsering** [comment]
After meeting changed the stitching method, what I did is. I took nine images and then stitch square as 3*3 and then take a random image from those 9. take that random image and half it and then scale it by 4 times and put it in the middle, to keep the images information, I have put `work_id_imagegroup_last_four_digit_of_images`. example `W1KG1247_I1KG12610673_0159_0205_0238_0347_0608_0550_0279_0040.jpg`
![image](https://github.com/OpenPecha/Requests/assets/43548581/cc157d08-f642-4f16-b310-0d28539dd790)
