### ISSUE TITLE
[RFC0073] Text descriptions

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/Requests#305]
# [RFC0073] Text descriptions

## Named Concepts
JSON:  A standard text-based format for representing structured data based on JavaScript object syntax
CSV: A text file format that uses commas to separate values.

## Summary
- End-user can view all libraries listed on Text landing page in `pecha.org` and on clicking the particular library user are can able to see all the Texts available under the library. 
- On clicking a particular Text , a new page will open and here user can see detial descriptions of the Text. The new page wiil be sectioned into two part
   - left section: In this section, list of `chapters` and `versions`of the Text  will be listed
   - right section: In this section, user can see short description of text will be available and Download feature will be there.Text can be download in various format like `CSV`, `JSON` and `Plan text`
   
## Dependencies
Render : pecha.org is currently deployed in Render
MongoDB: ALL the texts are stored in this database

## Justification
pacha.org is fork from sefaria.org. all the tools currently in pecha.org is same as `sefaria`

-  Why was the currently proposed design selected over alternatives?
`Sefaria` design provide all the features that are required for `Pecha.org`

- What would be the impact of going with one of the alternative approaches?
`Sefaira` is open souce project and our requirements are fulfilled by using Sefaria. So it is not necessary to go with alternative approaches as of now

## Implementation Steps
non coding 
- [x] Planning

Implementation

- [x] fixed hebrew number series to tibetan number series  
      Estimated time:  3hr
      Actual time:  
- [x] OpenPecha/Pecha.org#83
      Estimated time:  
      Actual time:  
- [ ] OpenPecha/Pecha.org#84
      Estimated time:  5-6hr
      Actual time:  
 - [ ] OpenPecha/Pecha.org#85
      Estimated time:  5-6hr
      Actual time:  
 - [x] OpenPecha/Pecha.org#86
     Estimated time:  5-6hr
      Actual time:  
 - [x] OpenPecha/Pecha.org#87
     Estimated time:  5-6hr
      Actual time:  

Testing 
- [ ] Unit testing

## Reviewed By
@tenkus47
