### ISSUE TITLE
[RFC0075] Preparing Test data for Layout Analysis

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/Requests#321]
# RFC0075: Preparing Test data for Layout Analysis

## Named Concepts
ttl: need to parse bdrc ttl file to get the work_id's info
s3 : BDRC images are stored on s3

## Summary
check the images used in the layout analysis training data and then list all the work ids and images used. Then randomly take 20 to 30 images that are not used in the training data. And then add to the the training data directory. after that we need to use the layout analysis model to get the class out of those image to see if they represent the training data classes or not. 

## Dependencies
boto3 and botocore : to use s3 via python package
rdf: to parse the ttl

## Infrastructures
*Include all the infrastructure required for running the task, such as S3 bucket, EC2 server, etc.*

## Design Illustrations
*Include all the pictorial representation of your implementation, such as flowchart, ER diagram, etc.*

## Justification
*Add justification for the strategies you have proposed above.*

> Why was the currently proposed design selected over alternatives?

> What would be the impact of going with one of the alternative approaches?

## Testing
 For testing I am gonna use the layout analysis inference.

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] Get the used images and collect all the work ids and then use that to randomly take images from that. 
      Estimated time:  3 Hours
      Actual time:  
- [ ] take the randomly taken images list and then check if it is already used in the training data or not and download if it is not used.
      Estimated time:  3 hours
      Actual time: 
- [ ] pipeline to use the layout analysis model to get the inference of the classes it predicts of the images downloaded.
      Estimated time: 8 hours
      Actual time:
- [ ] Reselect the images for the testing to be more representative, if need be after the analysis of the third step.
      Estimated time: NA
      Actual time:

## Reviewed By
@kaldan007

**Comment by kaldan007** [comment]
@ta4tsering can u add illustration of the workflow
