### ISSUE TITLE
[RFC0083] Monlam.ai file upload feature for each tools

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#330]
# RFC0083 Monlam.ai file upload feature for each tools

## Named Concepts
file Format :  image  -> .jpg  , .pdf
                     text ->  .docx , .txt
                     audio-> .mp4 ,.wav
## Summary

each tool should have ability to add file for conversion.

## Dependencies

[remix file upload](https://remix.run/docs/en/main/guides/file-uploads)

## Infrastructures
file might need to be store on s3.

## Design Illustrations
*Include all the pictorial representation of your implementation, such as flowchart, ER diagram, etc.*

## Justification
*Add justification for the strategies you have proposed above.*

## Testing
*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] fileUpload for MT
      Estimated time:  2 day
      Actual time:  

- [ ] error handling for invalid file format
- [ ] compiling the translation
- [ ] storing the input and output in s3
- [ ] shipping the translation to corresponding file format

- [ ] fileUpload for OCR  
      Estimated time:  2 day
      Actual time:  

- [ ] fileUpload for STT  
      Estimated time:  2day
      Actual time:  

- [ ] fileUpload for TTS 
      Estimated time:  2day
      Actual time:  

## Reviewed By
*Who has reviewed the RFC?*
