### ISSUE TITLE
[RFC0100] Latest mock up of our application in Figma

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#373]
# RFC0100: *Latest mock up of our application in Figma*

## Named Concepts
figma:  platform for building a ui design

## Summary
we need to design UI in figma

## Dependencies
figma

## Infrastructures
*Include all the infrastructure required for running the task, such as S3 bucket, EC2 server, etc.*

## Design Illustrations

full page design
https://monlam.ai

design for career page:
![image](https://github.com/OpenPecha/Requests/assets/42644738/a02482ab-4d94-4585-a91e-86ccaa17aa42)

## Justification

> Why was the currently proposed design selected over alternatives?

> What would be the impact of going with one of the alternative approaches?

## Testing
*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Implementation Steps
*List all the steps involved during implementation.*

- [ ]   Design figma for homepage
      Estimated time:  
      Actual time:  
- [ ]   Design figma for tools page
      Estimated time:  
      Actual time:  
- [ ]   Design figma for about page
      Estimated time:  
      Actual time:  

## Reviewed By
*Who has reviewed the RFC?*
