### ISSUE TITLE
[RFC0098]  Adding a Social Media Share Button option for Monlam AI Model Outputs

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#374]
# RFC0098  Adding a Social Media Share Button option for Monlam AI Model Outputs

## Named Concepts
*Explain any new concepts introduced in this request.*

## Summary
button onclick will show the shareable link as well as each social media icon .

the url structure will be https://monlam.ai/share/{id}
here id will be different for each inference.

## Dependencies
facebook and tweeter share API

## Infrastructures
*Include all the infrastructure required for running the task, such as S3 bucket, EC2 server, etc.*

## Design Illustrations
on click of button 
![image](https://github.com/OpenPecha/Requests/assets/42644738/0f56f5d6-f9b8-4cc3-9125-7e210861d9b9)

## Justification
*Add justification for the strategies you have proposed above.*

> Why was the currently proposed design selected over alternatives?

> What would be the impact of going with one of the alternative approaches?

## Testing
*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Implementation Steps
*List all the steps involved during implementation.*

- [x] Button for sharing output
      Estimated time:  0.5 day
      Actual time:  

- [x] UI for showing read-only page shared data
      Estimated time:  1.5 day
      Actual time:  
- [x]  backend integration with Facebook and tweeter API 
      Estimated time:  1 day
      Actual time:  

## Reviewed By
*Who has reviewed the RFC?*
