### ISSUE TITLE
[RFC0109] All the inputs or inferences of Monlam AI Model need to be stored

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/Requests#375]
#RFC0109 All the inputs or inferences of Monlam AI Model need to be stored

## Named Concepts
inference: input for model and Output data that are produced by the Monlam AI models.

## Summary
here we need to store all the input text and raw base64 speech in database. for that we need button on MT for submitting and not debounce .

conditions:
the inference data will be stored when 

-  whenever we get response from model api.
- whenever we submit the edited output data , edited should have a separate column in database.
- like and dislike will increase and decrease rating count accordingly .

## Dependencies

we need a way to get model version , either document/hosted .

## Infrastructures
*Include all the infrastructure required for running the task, such as S3 bucket, EC2 server, etc.*

## Design Illustrations

Required column in database 
![image](https://github.com/OpenPecha/Requests/assets/42644738/d60d1af0-6c86-4224-80aa-5689bd5e139f)

## Justification
*Add justification for the strategies you have proposed above.*

> Why was the currently proposed design selected over alternatives?

> What would be the impact of going with one of the alternative approaches?

## Testing
*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Implementation Steps
*List all the steps involved during implementation.*

- [x] model schema design on prisma + migration    
      Estimated time:  0.5 day
      Actual time:  

- [x] like / dislike rating implement
      Estimated time:  0.5 day
      Actual time:  

- [x] post API design for each models
      Estimated time:  2 day
      Actual time:  

## Reviewed By
@kaldan007

**Comment by tenkus47** [comment]
the data are stored on database for 3 models ,ocr is not complete yet.
