### ISSUE TITLE
[RFC0116]: Filter out bad transcriptions for STT_MV

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/Requests#399]
# RFC0116: *Filter out bad transcriptions for STT_MV
*

## Named Concepts
STT_MV: Speech-to-text for Tibetan movie/TV program transcriptions.
CER: Character Error Rate, a metric for transcription quality.

## Summary
*Developing a script to filter out poor-quality transcriptions from Tibetan movie and TV program segments. This will help in improving the stt model performance by feeding it with stt data that are of high quality. *

## Dependencies
1. datasets 
2. transformers
3.  pandas
4. evaluate 

## Infrastructures
[stt-model-evaluation](https://github.com/OpenPecha/stt-model-evaluation/blob/main/evaluate.ipynb)

## Design Illustrations
*Include all the pictorial representation of your implementation, such as flowchart, ER diagram, etc.*

## Justification
This approach uses audio quality assessment and CER metrics to ensure data reliability. Alternative methods, like manual checking, are time-consuming and less scalable.

## Testing
1. Unit tests for each script component.
5. Evaluation using a subset of the dataset to assess filtering accuracy.

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] PR 1 read the packages for stt transcript quality analysis
      Estimated time:  
      Actual time:  
- [ ] PR 2 filter the STT_MV data from hugging face and download 
      Estimated time:  
      Actual time:  
- [ ] PR 3 install the botok and hunspell packages with tibetan dictionary
      Estimated time:  
      Actual time:  
- [ ] PR 4 get the list of transcription of each stt_mv data 
      Estimated time:  
      Actual time:  
- [ ] PR 5 normalize the transcription using unicode normalizer from botok library
      Estimated time:  
      Actual time:  
- [ ] PR 6 check the cer using hunspell with python
      Estimated time:  
      Actual time:  

- [ ] PR 6 make a list of stt_mv with high cer detected using hunspell.
      Estimated time:  
      Actual time:  

## Reviewed By
* @kaldan007 
* @spsither *
