### ISSUE TITLE
[RFC00146]: Modify New Pecha.org's UI

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Requests#414]
# [RFC00146]: Modify New Pecha.org's UI

## Named Concepts
UI : User Interface
Pecha.org : Buddhist text interface website

## Summary
The newly deployed sefaria instance named pecha.org need UI modification in order to fit the Buddhist text reader's preference. So I am going to make those needed UI change.

## Dependencies
github action, docker, render

## Infrastructures
mongodb

## Design Illustrations
![flow chart](https://github.com/OpenPecha/Requests/assets/102473656/dfea7c45-0ad1-4acc-a36f-ad0bf0e519f6)

## Justification
Having a particular feature branch where same type of features are pushed are necessary for feature sharing with sefaria in future.
Testing on staging branch before committing to production branch is necessary in order to avoid mistakes on production branch. 

## Testing
Locally run pecha.org test and staging branch deployed test are necessary to avoid future mistakes on production.

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] logo related change   
      Estimated time:  1 hour
      Actual time:  
- [ ] change text direction from rtl to ltr
      Estimated time:  3 hour
      Actual time:  
- [ ] sefaria feature disable 
      Estimated time:  2 hour
      Actual time:  

## Reviewed By
*Who has reviewed the RFC?*
