### ISSUE TITLE
RFC00148: Localization for Pecha.org (Language : Tibetan)

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Requests#433]
# RFC00148: Localization for Pecha.org (Language : Tibetan)

## Named Concepts
Localization : The process of adapting a product's translation to a specific country or region.

## Summary
Pecha.org which is an instance of Sefaria, currently support two language (English and Hebrew). We need to replace the Hebrew language with Tibetan language.

## Dependencies
Github action, docker, render

## Infrastructures
mongodb

## Design Illustrations
![localization_implementation](https://github.com/OpenPecha/Requests/assets/102473656/06e2a556-fd8d-4617-a620-aedba84341ca)

## Justification
We used transifex with this task (localization of bo) because transifex makes the developers task much easier to transfer the translated files after translator finished his/her work.

## Testing
We can test the result from the feature branch it self or can test on staging.pecha.org.

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] Prepare 3 files 
      Estimated time:  1 hour
      Actual time:  
- [ ] Sync the files with transifex and edit it's setting
      Estimated time:  1 hour
      Actual time:  
- [ ] Configure translated files on django and react 
      Estimated time:  1 hour
      Actual time:  
- [ ] Apply string_extra.js strings on Pecha.org code manually
      Estimated time:  3 hour
      Actual time:  
## Reviewed By
*Who has reviewed the RFC?*
