### ISSUE TITLE
RFC0125: Technical documentation about STT and TTS workflow for other developers

### ISSUE THREAD

**Issue by spsither** [OpenPecha/Requests#450]
# RFC0125: Technical documentation about STT and TTS workflow for other developers

## Summary
Write technical documentation about STT and TTS workflow for future reference and other developers.

## Dependencies
- [pecha-tools-for-stt](https://github.com/OpenPecha/pecha-tools-for-stt)
- [saymore-report-generator](https://github.com/OpenPecha/saymore-report-generator)
- [stt-combine-datasets](https://github.com/OpenPecha/stt-combine-datasets)
- [stt-wav2vec2](https://github.com/OpenPecha/stt-wav2vec2)
- [stt-whisper](https://github.com/OpenPecha/stt-whisper)
- [stt-model-evaluation](https://github.com/OpenPecha/stt-model-evaluation)

## Justification

> Why was the currently proposed design selected over alternatives?

Writing documentation is a necessity. It helps with institutional memory.

> What would be the impact of going with one of the alternative approaches?

An alternative is to reinvent the wheel two months down the road.

## Implementation Steps
*List all the steps involved during implementation.*

- [ ] OpenPecha/stt-documentation#2
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#3
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#4
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#5
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#6
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#7
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#8
      Estimated time:  2 hours
      Actual time:  
- [ ] OpenPecha/stt-documentation#9
      Estimated time:  2 hours
      Actual time:  

## Reviewed By
*Who has reviewed the RFC?*
