### ISSUE TITLE
[RFC00]

### ISSUE THREAD

**Issue by 10kalden** [OpenPecha/Requests#463]
# RFC00139: *Create the font using the existing glyphs we cropped*

## Named Concepts
_Glyphs: A single representation of a character_

_Ligatures: A ligature refers to a special symbol formed by combining two or more letters into a single glyph_

_Font: The word font refers to a set of printable or displayable typography or text characters in a specific style and size._

_fonttools: fontTools is a library for manipulating fonts, written in Python. The project includes the TTX tool, that can convert TrueType and OpenType fonts to and from an XML text format, which is also called TTX._

## Summary
*Write a script to select 10 random images of cropped glyphs of each character and create the font using existing tools.*

## Dependencies
*fonttools, sgvwrite, numpy, jsonlines, PIL*

## Infrastructures
*S3 bucket: All the glyphs images and annotations are downloaded from S3 bucket.*

## Design Illustrations
![Work_flow_diagram](https://github.com/OpenPecha/Requests/assets/132426323/52ef9702-a1fb-4c30-80c2-94c696a765af)

## Justification
_This is a modification on the existing create_font tool
There is a total of almost 100 glyphs for each characters
The script will random select 10 glyph images to be converted into font_

## Testing
*TBD*

## Implementation Steps

- [ ] _Download the gylph files from the S3 bucket_
- [ ] _Parse the file and select only accepted result_
- [ ] _Write a script to select 10 random glyph images_
- [ ] _Create the font using create_font tool_

- [ ] PR 1 Modify the create_font tool based on need
      Estimated time: 1 hrs
      Actual time:  
- [ ] PR 2  
      Estimated time:  Write a script to select 10 random glyphs images  
      Estimated time: 2 hrs
      Actual time:  

## Reviewed By
@ta4tsering
