### ISSUE TITLE
RFC133: Creating a benchmark dataset for OCR

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/Requests#465]
# RFC00: *RFC Title*

## Summary
create benchmark dataset for OCR from all the transcribed line images, use them to filter out line images randomly from each batch or works.

## Dependencies
*Include all the dependencies you are going to use while implementing.*

## Infrastructures
*Include all the infrastructure required for running the task, such as S3 bucket, EC2 server, etc.*

## Design Illustrations
<img width="274" alt="Screenshot 2024-03-01 at 11 58 30 AM" src="https://github.com/OpenPecha/Requests/assets/43548581/821529b2-9347-42a8-b845-63fc2deca41c">

## Justification
This is the best method for now as it will be much quicker to take the benchmark data from the transcribed data then to take new images to be transcribed from scratch.

## Testing
*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Implementation Steps

- [ ] Download all the annotation jsonl from batch 1 - 18 and norbuletaka  batch 1-150.       
      Estimated time:  3 hr.
      Actual time:  
- [ ] Create a csv for each batch.
      Estimated time:  4 hr
      Actual time:  
- [ ] Randomly select 10% of images from each batch.
      Estimated time:  2 hr
      Actual time:  
- [ ] create csv for each transcripts of the training data and remove the above selected images.       
      Estimated time:  6 hr
      Actual time:  
- [ ] Delete the benchmark data images from the training data images.
      Estimated time:  6 hr
      Actual time:  
- [ ] Create a new folder with all the OCR training data in zip
      Estimated time:  8 hr
      Actual time:

## Reviewed By
@kaldan007

**Comment by kaldan007** [comment]
@ta4tsering we need to create separate benchmark for each writing style
we can mix ume in uchen benchmark as it won't be fair.

**Comment by ta4tsering** [comment]
Okay, will make it for Uchan only.
