### ISSUE TITLE
[RFC019] Create a tool to merge InterText files on Github

### ISSUE THREAD

**Issue by tenzin-chime** [OpenPecha/Requests#84]
<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

*Please add ref in specified format into `RFC` title, e.g `[RFC9999]` if corresponding RFW is `[RFW9999]`.*

*Please add into this `RFC` and related `PR's` titles `[RFC_id]` e.g `[RFC_9999]`.*

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

- **Alignment** - sentence to sentence mapping of a translation and its original. The alignment can be 1:1, 1 to many or 1 to none.
- **InterText** - https://wanthalf.saga.cz/intertext
- **InterText file format** - Set of 3 XML files respectively containing language A sentences, language B sentences and their mapping. [example files](https://github.com/OpenPecha/Requests/files/10447441/Updated-20230118T143842Z-001.zip)

<h2 id="summary">Summary</h2>

This tool will allow a multilingual aligners to merge InterText alignment files when pushing them on GitHub.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

- Create a dev env
- Create a module that extracts the bo file and cn file separately using RegEx.
- Define a function to merge the same structure xml file
- Iterate by using for loop to continue the tag p which is paragraph id of the next xml file
- Define a function that also update the tag s sentences of the paragraph which is same.
- Create a module to update the x.target of the merged intertext file.
- Create github action to parse the give xml files.

<h2 id="alternatives">Alternatives</h2>

TM files in .tmx or .xliff format can be merged in many CAT tools. The issue with that approach is that the segment order isn't always preserved and no such tool we tested support cross-order alignment.
Other existing tools such as Olifant are not very user friendly and only work with formats that don't preserve cross-order alignment.

<h3 id="rationale">Rationale</h3>

<em>

- Why the currently proposed design was selected over alternatives?
        - It will preserve the segment order.
- What would be the impact of going with one of the alternative approaches?
       - Not preserving order.
- Is the evaluation tentative, or is it recommended to use more time to evaluate different approaches?
       - No
</em>

<h2 id="drawbacks">Drawbacks</h2>

It cannot be merged three or more intertext text files all together.

<h2 id="useful-rererences">Useful References</h2>

https://wanthalf.saga.cz/intertext

<em>
  
- What similar work have we already successfully completed? : None
- Is this something that have already been built by others? : Yes but doesn't preserve segment order
- What other related learnings we have?:Github Action
- Are there useful academic literature or other articles related with this topic? (provide links):None
- Have we built a relevant prototype previously?:None
- Do we have a rough mock for the UI/UX?:None
- Do we have a schematic for the system?:None

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)? : Continuing the  alignment order
- Are there other requests with same or similar problems to solve? : None
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request? : None
- What other open requests are closely related with this request? : None
- Does this request depend on fulfillment of any other request? : None
- Does any other request depend on the fulfillment of this request?* : None

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

In future we can merge multiple languages.

<h2 id="infrastructure">Infrastructure</h2>

Not applicable

<h2 id="testing">Testing</h2>

Not yet done

<h2 id="documentation">Documentation</h2>

Not applicable yet

<h2 id="version-history">Version History</h2>

None

<h2 id="recordings">Recordings</h2>

None

## Work Phases
<h2 id="work-phases"></h2>

- [x] OpenPecha/intertext-files-merger#2
   Time Estimation: 15 mins.
   Time Taken:
- [x] OpenPecha/intertext-files-merger#3
   Time Estimation: 3 hours
   Time Taken:
- [x] OpenPecha/intertext-files-merger#4
   Time Estimation: 4 hours
   Time Taken:
- [x] OpenPecha/intertext-files-merger#5
   Time Estimation: 3 hours 
   Time Taken:
- [x] OpenPecha/intertext-files-merger#6
   Time Estimation:  3 hours
   Time Taken:
- [ ] OpenPecha/intertext-files-merger#7
   Time Estimation:  5 hours
   Time Taken:  

<h3 id="non-coding">Non-Coding</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

  - [x] OpenPecha/Requests#83
  - [ ] OpenPecha/intertext-files-merger#15
  - [ ] OpenPecha/intertext-files-merger#16

**Comment by kaldan007** [comment]
we need a way to pass the regrouped filename in order to make the workflow independent from certain file naming convention
